# Generated by Django 5.1.5 on 2025-01-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('editor', 'Editor'), ('author', 'Author'), ('contributor', 'Contributor'), ('subscriber', 'Subscriber')], default='subscriber', max_length=20),
        ),
    ]
